variables:
  IMAGE_NAME: brettrjonesdocker/nolimitappimage
  IMAGE_TAG: nlcdevimage-1.0.7 # for Qt 6.6.1 use nlcdevimage-1.0.5, for Qt 6.6.2 ise nlcdevimage-1.0.7


stages:
#  - build_image
#  - check_for_tagged_commit
  - compile_nlc_for_linux_and_android_os


# dummy pipeline so do not get Checking pipeline status forever when no tag is committed
#run_ci_only_for_tags:
#  stage: check_for_tagged_commit
#  rules:
#    - if: '$CI_COMMIT_TAG == null'
#  script:
#    - echo run ci only on tags
#    - env
#    - echo "Dummy job for merge-request"
#    - exit 0

compile_nlc_linux:
  stage: compile_nlc_for_linux_and_android_os
  when: manual
#  rules:
    #- if: '$CI_COMMIT_TAG != null'
    
  timeout: 6 hours

  # image derived from docker image carlonluca/qt-dev:6.6.2 with the following changes
  # install nlc build required libraries (most are already installed)
  # apt-get update
  # apt-get install build-essential cmake g++ git libglu1-mesa-dev uuid-dev nasm
  image: 
    name: $IMAGE_NAME:$IMAGE_TAG
    entrypoint: [""]

  before_script:
    - ls /builds/nolimitconnectapps/nolimitapp
    - cd /builds/nolimitconnectapps/nolimitapp
    - mkdir package
    - mkdir package/linux
    - mkdir package/android
    - mkdir dockerbuild
    - mkdir dockerbuild/nlcbuild
    - cd dockerbuild/nlcbuild
 
  script:
    - chmod 400 $SSH_NET_SRV_PRIV_KEY

    - rm -rf *
    - rm -rf ../../package/android
    - cmake -S ../.. -B . -DCMAKE_BUILD_TYPE=Release -DTARGET_OS_ANDROID=true -DMAKE_ENV=CI  -DQT_VERSION=6_6_2

    - echo 'start make'
    - make -j$(nproc)
    - echo 'make complete'

    - echo 'publish_android_package'
    - ls /builds/nolimitconnectapps/nolimitapp/dockerbuild/nlcbuild/nolimitgui/android-build//build/outputs/apk/debug
    - ssh -o StrictHostKeyChecking=no -i $SSH_NET_SRV_PRIV_KEY root@nolimitconnect.net 
    - scp -i $SSH_NET_SRV_PRIV_KEY -r /builds/nolimitconnectapps/nolimitapp/dockerbuild/nlcbuild/nolimitgui/android-build//build/outputs/apk/debug/*.apk root@nolimitconnect.net:/var/www/html/download/android

    - rm -rf *
    - rm -rf ../../package/linux
    - cmake -S ../.. -B . -DCMAKE_BUILD_TYPE=Release -DTARGET_OS_LINUX=true -DMAKE_ENV=CI  -DQT_VERSION=6_6_2
    - make -j$(nproc)
    - cpack -C CPackConfig.cmake
      
    - echo 'publish_linux_package'
    - ssh -o StrictHostKeyChecking=no -i $SSH_NET_SRV_PRIV_KEY root@nolimitconnect.net 
    - scp -i $SSH_NET_SRV_PRIV_KEY -r /builds/nolimitconnectapps/nolimitapp/package/linux/*.deb root@nolimitconnect.net:/var/www/html/download/linux

  # NOTE: artifacts are for testers only and NOT for general public users so use at your own risk
#  artifacts:
#    name: "NoLimitConnect_$CI_COMMIT_TAG"
#    paths:
#      - /builds/nolimitconnectapps/nolimitapp/package/linux/*.deb
      #- ../../package/android/*.apk

#    expire_in: 1 week  

  after_script:
    # TODO publish linux.deb and android.apk packages
