
add_compile_definitions(
    LIB_STATIC
    HAVE_CONFIG_H
    FILE_OFFSET_BITS=64
    ENABLE_NLC_PLAYER
)

add_compile_definitions(
    FT_DEBUG_LEVEL_ERROR=1
    DEBUG_LEVEL_TRACE=1
    FT2_BUILD_LIBRARY=1
    FT_MAKE_OPTION_SINGLE_OBJECT=1
)

add_compile_definitions(
    OPENSSL_NO_EC_NISTP_64_GCC_128 OPENSSL_NO_GMP OPENSSL_NO_JPAKE OPENSSL_NO_LIBUNBOUND OPENSSL_NO_MD2 OPENSSL_NO_RC5
    OPENSSL_NO_RFC3779 OPENSSL_NO_SCTP OPENSSL_NO_SSL_TRACE OPENSSL_NO_SSL2 OPENSSL_NO_STORE OPENSSL_NO_UNIT_TEST OPENSSL_NO_WEAK_SSL_CIPHERS
    NO_SYSLOG OPENSSL_THREADS _REENTRANT DSO_DLFCN HAVE_DLFCN_H m64 L_ENDIAN
    OPENSSL_NO_EC_NISTP_64_GCC_128
)

if(DEFINED TARGET_OS_WINDOWS)
    add_compile_definitions(
        DSO_WIN32
    )
endif()
