
#if defined(CONFIG_FFMPEG_H)

static const FFOutputFormat * const muxer_list[] = {
    &ff_a64_muxer,
    &ff_ac3_muxer,
    &ff_adts_muxer,
    &ff_adx_muxer,
#if CONFIG_AIFF_MUXER
    &ff_aiff_muxer,
#endif // CONFIG_AIFF_MUXER
    &ff_alp_muxer,
    &ff_amr_muxer,
    &ff_amv_muxer,
    &ff_apm_muxer,
    &ff_apng_muxer,
#if CONFIG_APTX_MUXER
    &ff_aptx_muxer,
#endif // CONFIG_APTX_MUXER
#if CONFIG_APTX_HD_MUXER
    &ff_aptx_hd_muxer,
#endif // CONFIG_APTX_HD_MUXER
    &ff_argo_asf_muxer,
    &ff_argo_cvg_muxer,
    &ff_asf_muxer,
    &ff_ass_muxer,
    &ff_ast_muxer,
    &ff_asf_stream_muxer,
    &ff_au_muxer,
#if CONFIG_AVI_MUXER
    &ff_avi_muxer,
#endif // CONFIG_AVI_MUXER
#if CONFIG_AVIF_MUXER
    &ff_avif_muxer,
#endif // CONFIG_AVIF_MUXER
    &ff_avm2_muxer,
    &ff_avs2_muxer,
    &ff_avs3_muxer,
    &ff_bit_muxer,
#if CONFIG_CAF_MUXER
    &ff_caf_muxer,
#endif // CONFIG_CAF_MUXER
    &ff_cavsvideo_muxer,
    &ff_codec2_muxer,
    &ff_codec2raw_muxer,
    &ff_crc_muxer,
    &ff_dash_muxer,
    &ff_data_muxer,
    &ff_daud_muxer,
    &ff_dfpwm_muxer,
    &ff_dirac_muxer,
    &ff_dnxhd_muxer,
    &ff_dts_muxer,
    &ff_dv_muxer,
    &ff_eac3_muxer,
#if CONFIG_F4V_MUXER
    &ff_f4v_muxer,
#endif // CONFIG_F4V_MUXER
    &ff_ffmetadata_muxer,
    &ff_fifo_muxer,
    &ff_fifo_test_muxer,
    &ff_filmstrip_muxer,
    &ff_fits_muxer,
    &ff_flac_muxer,
    &ff_flv_muxer,
    &ff_framecrc_muxer,
    &ff_framehash_muxer,
    &ff_framemd5_muxer,
    &ff_g722_muxer,
    &ff_g723_1_muxer,
    &ff_g726_muxer,
    &ff_g726le_muxer,
    &ff_gif_muxer,
    &ff_gsm_muxer,
    &ff_gxf_muxer,
    &ff_h261_muxer,
    &ff_h263_muxer,
    &ff_h264_muxer,
    &ff_hash_muxer,
    &ff_hds_muxer,
    &ff_hevc_muxer,
#if CONFIG_HLS_MUXER
    &ff_hls_muxer,
#endif // CONFIG_HLS_MUXER
    &ff_ico_muxer,
    &ff_ilbc_muxer,
    &ff_image2_muxer,
    &ff_image2pipe_muxer,
#if CONFIG_IPOD_MUXER
    &ff_ipod_muxer,
#endif // CONFIG_IPOD_MUXER
    &ff_ircam_muxer,
#if CONFIG_ISMV_MUXER
    &ff_ismv_muxer,
#endif // CONFIG_ISMV_MUXER
    &ff_ivf_muxer,
    &ff_jacosub_muxer,
    &ff_kvag_muxer,
    &ff_latm_muxer,
    &ff_lrc_muxer,
    &ff_m4v_muxer,
    &ff_md5_muxer,
    &ff_matroska_muxer,
    &ff_matroska_audio_muxer,
    &ff_microdvd_muxer,
    &ff_mjpeg_muxer,
    &ff_mlp_muxer,
    &ff_mmf_muxer,
#if CONFIG_MOV_MUXER
    &ff_mov_muxer,
#endif // CONFIG_MOV_MUXER
    &ff_mp2_muxer,
    &ff_mp3_muxer,
#if CONFIG_MP4_MUXER
    &ff_mp4_muxer,
#endif // CONFIG_MP4_MUXER
    &ff_mpeg1system_muxer,
    &ff_mpeg1vcd_muxer,
    &ff_mpeg1video_muxer,
    &ff_mpeg2dvd_muxer,
    &ff_mpeg2svcd_muxer,
    &ff_mpeg2video_muxer,
    &ff_mpeg2vob_muxer,
#if CONFIG_MPEGTS_MUXER
    &ff_mpegts_muxer,
#endif // CONFIG_MPEGTS_MUXER
    &ff_mpjpeg_muxer,
    &ff_mxf_muxer,
    &ff_mxf_d10_muxer,
    &ff_mxf_opatom_muxer,
    &ff_null_muxer,
    &ff_nut_muxer,
    &ff_obu_muxer,
    &ff_oga_muxer,
    &ff_ogg_muxer,
    &ff_ogv_muxer,
    &ff_oma_muxer,
    &ff_opus_muxer,
    &ff_pcm_alaw_muxer,
    &ff_pcm_mulaw_muxer,
    &ff_pcm_vidc_muxer,
    &ff_pcm_f64be_muxer,
    &ff_pcm_f64le_muxer,
    &ff_pcm_f32be_muxer,
    &ff_pcm_f32le_muxer,
    &ff_pcm_s32be_muxer,
    &ff_pcm_s32le_muxer,
    &ff_pcm_s24be_muxer,
    &ff_pcm_s24le_muxer,
    &ff_pcm_s16be_muxer,
    &ff_pcm_s16le_muxer,
    &ff_pcm_s8_muxer,
    &ff_pcm_u32be_muxer,
    &ff_pcm_u32le_muxer,
    &ff_pcm_u24be_muxer,
    &ff_pcm_u24le_muxer,
    &ff_pcm_u16be_muxer,
    &ff_pcm_u16le_muxer,
    &ff_pcm_u8_muxer,
#if CONFIG_PSP_MUXER
    &ff_psp_muxer,
#endif // CONFIG_PSP_MUXER
    &ff_rawvideo_muxer,
    &ff_rm_muxer,
    &ff_roq_muxer,
    &ff_rso_muxer,
    &ff_rtp_muxer,
    &ff_rtp_mpegts_muxer,
    &ff_rtsp_muxer,
    &ff_sap_muxer,
    &ff_sbc_muxer,
    &ff_scc_muxer,
    &ff_segafilm_muxer,
    &ff_segment_muxer,
    &ff_stream_segment_muxer,
    &ff_smjpeg_muxer,
    &ff_smoothstreaming_muxer,
    &ff_sox_muxer,
    &ff_spx_muxer,
    &ff_spdif_muxer,
    &ff_srt_muxer,
    &ff_streamhash_muxer,
    &ff_sup_muxer,
    &ff_swf_muxer,
    &ff_tee_muxer,
#if CONFIG_TG2_MUXER
    &ff_tg2_muxer,
#endif // CONFIG_TG2_MUXER
#if CONFIG_TGP_MUXER
    &ff_tgp_muxer,
#endif // CONFIG_TGP_MUXER
    &ff_mkvtimestamp_v2_muxer,
    &ff_truehd_muxer,
    &ff_tta_muxer,
    &ff_ttml_muxer,
    &ff_uncodedframecrc_muxer,
    &ff_vc1_muxer,
    &ff_vc1t_muxer,
    &ff_voc_muxer,
    &ff_w64_muxer,
    &ff_wav_muxer,
    &ff_webm_muxer,
    &ff_webm_dash_manifest_muxer,
    &ff_webm_chunk_muxer,
    &ff_webp_muxer,
    &ff_webvtt_muxer,
    &ff_wsaud_muxer,
#if CONFIG_WTV_MUXER
    &ff_wtv_muxer,
#endif // CONFIG_WTV_MUXER
    &ff_wv_muxer,
    &ff_yuv4mpegpipe_muxer,
    NULL };

#endif // defined(CONFIG_FFMPEG_H)